auction/item/models.py
from .. import db
from enum import Enum
import os
import uuid
from werkzeug.utils import secure_filename
from ..utils import JSON, humanise
from datetime import datetime
from ..bid.models import Bid


class Categories(Enum):
    '''Categories Enum'''

    Oil = 1
    Watercolor = 2
    Pastel = 3
    Acrylic = 4
    Charcoal_Drawing = 5
    Coloured_Pencil = 6
    Pencil_Sketch = 7
    Ink = 8
    Glass = 9
    Ball_Point_Pen_Art = 10
    Collage = 11
    Sand = 12
    Spray = 13
    Digital = 14
    Graffiti = 15
    Scroll = 16
    Water_Miscible_Oil_Paints = 17

    @classmethod
    def choices(cls):
        '''Returns choices for SelectField'''
        return [(choice.value, choice.name.replace('_', ' '))
                for choice in cls]


class Item(db.Model, JSON):
    '''Item database model'''
    __tablename__ = "items"

    # Identifier fields
    id = db.Column(db.Integer, unique=True, primary_key=True)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    open = db.Column(db.Boolean, nullable=False, default=True)

    # User fields
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('items', lazy=True))

    # Descriptive fields
    name = db.Column(db.String(120), nullable=False)
    description = db.Column(db.String(240), nullable=False)
    image = db.Column(db.String(120), nullable=False)
    category = db.Column(db.Integer, nullable=False)
    starting_price = db.Column(db.Integer, nullable=False)

    # Bids
    bids = db.relationship('Bid')

    # Initialiser function
    def __init__(self, form, user_id):
        '''The initialiser function for an item when passing a form'''
        self.user_id = user_id

        # get values from form
        self.name = form.name.data
        self.description = form.description.data
        self.category = form.category.data
        self.starting_price = form.starting_price.data

        # get file extension using last item after split of filename on '.'
        extension = secure_filename(form.image.data.filename).split('.')[-1]

        # join random uuid and extension to make filename
        self.image = '.'.join([str(uuid.uuid1()), extension])

        # make image path using filename and save image
        image_path = os.path.join('auction/static/uploads', self.image)
        form.image.data.save(image_path)

    # Humanise functions
    def category_humanise(self):
        '''Returns a prettified category'''
        return Categories(self.category).name.replace('_', ' ')

    def starting_price_humanise(self):
        '''Returns a prettified starting price'''
        return 'AUD$' + str(self.starting_price)

    def date_humanise(self):
        '''Returns humanised time difference'''
        return humanise(self.date)

# Bid functions
    def bid_count(self):
        '''Returns how many bids have been made'''
        return Bid.query.filter_by(item_id=self.id).count()

    def top_bid(self):
        '''Returns the highest bid if there is one'''
        bid = Bid.query.filter_by(item_id=self.id).order_by(
            Bid.bid.desc()).first()

        if bid is None:
            return self.starting_price

        return bid.bid

    def top_bid_humanise(self):
        '''Returns the highest bid if there is one'''
        bid = Bid.query.filter_by(item_id=self.id).order_by(
            Bid.bid.desc()).first()

        if bid is None:
            return self.starting_price_humanise()

        return 'AUD$' + str(bid.bid)

    def top_bid_date_humanise(self):
        bid = Bid.query.filter_by(item_id=self.id).order_by(
            Bid.bid.desc()).first()

        if bid is None:
            return self.date_humanise()

        return humanise(bid.date)

auction/item/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField, TextAreaField
from wtforms.validators import InputRequired, NumberRange
from flask_wtf.file import FileField, FileAllowed, FileRequired
from .models import Categories


class ItemForm(FlaskForm):
    '''Item form'''
    name = StringField("Name", validators=[InputRequired()])
    description = TextAreaField("Description", validators=[InputRequired()])
    starting_price = IntegerField(
        "Starting Price", validators=[InputRequired(),
                                      NumberRange(min=1)])
    category = SelectField("Categories",
                           choices=Categories.choices(),
                           coerce=int)
    image = FileField(
        "Image",
        validators=[FileRequired(),
                    FileAllowed(['jpg', 'jpeg', 'png'])])

    submit = SubmitField("Submit")

auction/item/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, session
from flask_login import login_required, current_user
from .forms import ItemForm
from .. import db
from .models import Item
from ..watchlist.models import WatchlistItem

# init item blueprint
item_bp = Blueprint("item", __name__, url_prefix="/item")


# get items of user
# GET - returns all items of a particular user
@item_bp.route('', methods=['GET', 'POST'])
@login_required
def items():
    items = Item.query.filter_by(user_id=current_user.id).all()

    return render_template('item/index.html', title='Items', items=items)


# get item by id
# GET - returns an item
@item_bp.route("/<id>", methods=['GET', 'POST'])
def index(id):
    item = Item.query.filter_by(id=id).first()
    watched = None

    if item is None:
        abort(404)

    if current_user:
        user_id = current_user.id
        watched = WatchlistItem.query.filter_by(user_id=user_id,
                                                item_id=item.id).first()

    return render_template("item/item.html",
                           title=item.name,
                           item=item,
                           watched=watched)


# create new item
# GET - returns create item form
# POST - posts create item form to database
@item_bp.route("/create", methods=['GET', 'POST'])
@login_required
def create():
    user_id = current_user.id
    form = ItemForm()

    # action if form is validated when submitted
    if form.validate_on_submit():
        # create item from values
        item = Item(form, user_id)

        # save item to db
        db.session.add(item)
        db.session.commit()
        # db.session.save()

        # flash and return to home screen
        flash('Item created!', 'success')
        return redirect(url_for('item.index', id=item.id))

    # return template if the form hasn't validated
    return render_template('item/create.html', form=form, title="Create Item")


@item_bp.route('/<id>/close', methods=['GET'])
@login_required
def close(id):
    user_id = current_user.id
    item = Item.query.filter_by(id=id, user_id=user_id, open=True).first()

    if item is None:
        abort(400)

    item.open = False

    db.session.commit()

    # flash and return to home screen
    flash('Auction closed!', 'success')
    return redirect(url_for('item.index', id=id))

auction/watchlist/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, abort
from .models import WatchlistItem
from .. import db
from flask_login import login_required, current_user

# init user blueprint
watchlist_bp = Blueprint("watchlist", __name__, url_prefix="/watchlist")


# get all watchlist items of user
# GET - returns an watchlist items
@watchlist_bp.route("", methods=['GET'])
@login_required
def index():
    watchlist = WatchlistItem.query.filter_by(user_id=current_user.id).all()
    return render_template("watchlist.html",
                           title="Watchlist",
                           watchlist=watchlist)


# remove a watched item from users watchlist
# POST - removes item
@watchlist_bp.route('/<item_id>/remove', methods=['GET'])
@login_required
def remove(item_id):
    user_id = current_user.id

    query = WatchlistItem.query.filter_by(item_id=item_id, user_id=user_id)
    watchlist_item = query.first()

    if watchlist_item is not None:
        query.delete()
        db.session.commit()

        flash('Watchlist Item removed!', 'success')
        return redirect(url_for('watchlist.index'))

    abort(400)


@watchlist_bp.route('/<item_id>/add', methods=['GET'])
@login_required
def add(item_id):
    user_id = current_user.id

    exists = WatchlistItem.query.filter_by(user_id=user_id,
                                           item_id=item_id).first()

    if exists:
        flash('Item already watched!', 'danger')
        return redirect(url_for('item.index', id=item_id))

    watched = WatchlistItem(user_id, item_id)

    db.session.add(watched)
    db.session.commit()

    # flash and return to watchlist screen
    flash('Item added to Watchlist!', 'success')
    return redirect(url_for('watchlist.index'))

auction/templates/item/create.html
{% extends "_layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<main class="py-5">
  <section class="container">
    <div class="row g-3">
      <div class="paper p-4 col-md-10 offset-md-1 offset-lg-2 col-lg-8">
      
        <h2 class="gutter">{{ title }}</h2>

        {{wtf.quick_form(form)}}
      </div>
    </div>
</main>
{% endblock content %}

auction/templates/item/index.html
{% extends "_layout.html" %}
{% block content %}
<main class="py-5" style="min-height: 750px;">
  <section class="container paper px-0">
    <nav class="navbar my-2 p-4">
      <h2 class="my-auto">Items</h2>

      <li class="nav-item d-flex content-center align-center">
        <a class="mx-2 btn btn-dark" type="button" href="{{ url_for('item.create') }}">Create Item</a>
      </li>
    </nav>

    <section class="list-group">

      {% if items|length %}
      {% for item in items %}
      <div class="list-group-item  d-flex align-items-center">

        <div
          role="img" 
          aria-label="{{ item.name }}"
          style="width: 5rem; height: 5rem; background-image: url({{ url_for('static', filename='uploads/' + item.image) }}); background-size: cover; background-position: center;" 
          class="shadow object-cover mr-3">
        </div>
        
        <div class="flex-grow-1">
          <div class="d-flex w-100 justify-content-between">

            <div>
              <h5 class="d-inline mt-2 mb-1">{{ item.name }}</h5>
              {% if item.open %}
              <span class="ml-md-3 my-2 my-md-0 badge bg-success rounded-pill float-md-right" data-toggle="tooltip"
                data-placement="bottom" title="Bid open!">{{ item.starting_price_humanise() }}</span>
              {% else %}
              <span class="ml-md-3 my-2 my-md-0 badge bg-danger rounded-pill float-md-right" data-toggle="tooltip"
                data-placement="bottom" title="Bid closed!">{{ item.starting_price_humanise() }}</span>
              {% endif %}
            </div>

            <div>
              <a href="{{ url_for('item.index', id=item.id) }}" class="btn btn-primary my-auto mr-3">View Item</a>

              <a href="{{ url_for('bid.item', id=item.id) }}" class="btn btn-success my-auto mr-3">View Bids</a>

              {% if item.open %}
              <a href="{{ url_for('item.close', id=item.id) }}" class="btn btn-danger my-auto mr-3">Close</a>
              {% endif %}

              <small class="text-muted">{{ item.date_humanise() }}</small>
            </div>

          </div>
        </div>

      </div>
      {% endfor %}
      {% else %}
      <div href="#" class="list-group-item d-flex align-items-center">
        <small class="w-100 text-center font-weight-light my-5 py-5">Add items and keep track of them
          here!</small>
      </div>
      {% endif %}


    </section>

</main>
{% endblock content %}

auction/templates/item/item.html
{% extends "_layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<main class="py-5">
  <section class="container">
    <section class="row mb-5">
      <article class="col-lg-8">
        <img src="{{ url_for('static', filename='uploads/' + item.image) }}" class="shadow h-100 object-cover w-100"
          alt="Item">
      </article>

      <article class="col-lg-4">
        <div class="paper gutter p-4">
          <div class="float-right">

            {% if item.open %}
            <span class="ml-3 mr-1 badge bg-success white rounded-pill" data-toggle="tooltip" data-placement="bottom"
              title="Auction open!">{{ item.starting_price_humanise() }}</span>
            {% else %}
            <span class="ml-3 mr-1 badge bg-danger white rounded-pill" data-toggle="tooltip" data-placement="bottom"
              title="Auction closed!">{{ item.starting_price_humanise() }}</span>
            {% endif %}

            <span class="badge bg-dark white rounded-pill" data-toggle="tooltip" data-placement="bottom"
              title="Category">{{ item.category_humanise() }}</span>
          </div>

          <h2 class="gutter">{{ item.name }}</h2>

          <p>{{ item.description }}</p>

          <small class="font-weight-light">Listed {{ item.date_humanise() }} by {{ item.user.name }}</small>
        </div>

        <div class="paper gutter p-4">
           <span class="ml-md-3 my-2 my-md-0 badge bg-dark rounded-pill float-md-right">{{ item.bid_count() }} bids</span>
          <h3 class="gutter">Latest bid</h3>
          
          <div>
            {% if item.bid_count() > 0 %}
            <p class="text-muted float-right">{{ item.top_bid_date_humanise() }}</p>
            <p>{{ item.top_bid_humanise() }}</p>
            {% else %}
            <small>No bids</small>
            {% endif %}
          </div>
        </div>

        {% if item.open %}
        <div class="paper gutter p-4">
          <h3 class="gutter">Actions</h3>
          <div>
            {% if current_user.is_authenticated %}
            {% if current_user.id != item.user_id %}
            {% if watched %}
            <a href="{{ url_for('watchlist.remove', item_id=item.id) }}" class="btn btn-danger w-100 mb-2">
              Remove from Watchlist
            </a>
            {% else %}
            <a href="{{ url_for('watchlist.add', item_id=item.id) }}" class="btn btn-primary w-100 mb-2">
              Add to Watchlist
            </a>
            {% endif %}
            <a href="{{ url_for('bid.item', id=item.id) }}" class="btn btn-success w-100 mb-2">
              Bid
            </a>
            {% else %}
            <a href="{{ url_for('item.close', id=item.id) }}" class="btn btn-danger w-100 mb-2">
              Close auction
            </a>
            <a href="{{ url_for('bid.item', id=item.id) }}" class="btn btn-success w-100 mb-2">
              View bids
            </a>
            {% endif %}
            {% else %}
            <small class="font-weight-light">
              <a href="{{ url_for('auth.login') }}">Login</a>
              or
              <a href="{{ url_for('auth.register') }}">register</a>
              to bid
            </small>
            {% endif %}

          </div>
        </div>
        {% endif %}

      </article>
    </section>
</main>

{% endblock content %}