auction/item/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, session
from flask_login import login_required, current_user
from .forms import ItemForm
from .. import db
from .models import Item
from ..watchlist.models import WatchlistItem

# init item blueprint
item_bp = Blueprint("item", __name__, url_prefix="/item")


# get items of user
# GET - returns all items of a particular user
@item_bp.route('', methods=['GET', 'POST'])
@login_required
def items():
    items = Item.query.filter_by(user_id=current_user.id).all()

    return render_template('item/index.html', title='Items', items=items)


# get item by id
# GET - returns an item
@item_bp.route("/<id>", methods=['GET', 'POST'])
def index(id):
    item = Item.query.filter_by(id=id).first()
    watched = None

    if item is None:
        abort(404)

    if current_user:
        user_id = current_user.id
        watched = WatchlistItem.query.filter_by(user_id=user_id,
                                                item_id=item.id).first()

    return render_template("item/item.html",
                           title=item.name,
                           item=item,
                           watched=watched)


# create new item
# GET - returns create item form
# POST - posts create item form to database
@item_bp.route("/create", methods=['GET', 'POST'])
@login_required
def create():
    user_id = current_user.id
    form = ItemForm()

    # action if form is validated when submitted
    if form.validate_on_submit():
        # create item from values
        item = Item(form, user_id)

        # save item to db
        db.session.add(item)
        db.session.commit()
        # db.session.save()

        # flash and return to home screen
        flash('Item created!', 'success')
        return redirect(url_for('item.index', id=item.id))

    # return template if the form hasn't validated
    return render_template('item/create.html', form=form, title="Create Item")


@item_bp.route('/<id>/close', methods=['GET'])
@login_required
def close(id):
    user_id = current_user.id
    item = Item.query.filter_by(id=id, user_id=user_id, open=True).first()

    if item is None:
        abort(400)

    item.open = False

    db.session.commit()

    # flash and return to home screen
    flash('Auction closed!', 'success')
    return redirect(url_for('item.index', id=id))

auction/views.py
from flask import Blueprint, render_template
from .item.models import Item
from .forms import FilterForm
from sqlalchemy import or_

bp = Blueprint('main', __name__)


# get items of user
# GET - returns all items
@bp.route('/', methods=['GET', 'POST'])
def index():
    form = FilterForm()

    query = Item.query

    if form.validate_on_submit():
        search = '%{search}%'.format(search=form.search.data)
        category = form.category.data

        query = query.filter(
            or_(Item.name.like(search), Item.description.like(search)))

        if (category > 0):
            query = query.filter_by(category=category)

    items = query.order_by(Item.date.desc()).all()

    return render_template('index.html', title='Items', items=items, form=form)

auction/templates/components/footer.html
<footer class="py-5 text-muted">
	<div class="container">
		<p class="float-right">
			<a href="#">Back to top</a>
		</p>
		<p>Auction Site 2020 ©</p>
	</div>
</footer>

auction/templates/components/nav.html
<section>
	<nav class="navbar navbar-expand-lg navbar-light outline-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ url_for('main.index') }}">
				Paintr
				<svg width="1.5rem" height="1.5rem" viewBox="0 0 16 16" class="bi bi-easel" fill="currentColor"
					xmlns="http://www.w3.org/2000/svg">
					<path
						d="M8.473.337a.5.5 0 0 0-.946 0L6.954 2h2.092L8.473.337zM12.15 11h-1.058l1.435 4.163a.5.5 0 0 0 .946-.326L12.15 11zM8.5 11h-1v2.5a.5.5 0 0 0 1 0V11zm-3.592 0H3.85l-1.323 3.837a.5.5 0 1 0 .946.326L4.908 11z" />
					<path fill-rule="evenodd"
						d="M14 3H2v7h12V3zM2 2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2z" />
				</svg>
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Browse</a>
					</li>
					<li class="nav-item d-flex content-center align-center">
						<a class="mx-2 btn btn-dark" type="button" href="{{ url_for('item.create') }}">List Item</a>
					</li>
				</ul>


				<ul class="navbar-nav ml-2 mb-2 mb-lg-0">

					{% if current_user.is_authenticated %}

					<li class="nav-item dropdown dropleft">
						<a class="nav-link dropdown-toggle" style="color:black;" href="#" id="navbarDropdown"
							role="button" data-toggle="dropdown" aria-expanded="false">
							<svg width="1.5rem" height="1.5rem" viewBox="0 0 16 16" class="bi bi-person-circle"
								fill="#000" xmlns="http://www.w3.org/2000/svg">
								<path
									d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z" />
								<path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
								<path fill-rule="evenodd"
									d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
							</svg>
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li class="dropdown-item"><strong>{{current_user.name}}</strong></li>
							<li>
								<hr class="dropdown-divider">
							</li>
							<li><a class="dropdown-item" href="{{ url_for('item.items') }}">Items</a></li>
							<li><a class="dropdown-item" href="{{ url_for('watchlist.index') }}">Watchlist</a></li>
							<li>
								<hr class="dropdown-divider">
							</li>
							<li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
						</ul>
					</li>

					{% else %}

					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Login</a>
					</li>

					<li class="nav-item">
						<a class="nav-link active" aria-current="page"
							href="{{ url_for('auth.register') }}">Register</a>
					</li>

					{% endif %}

				</ul>

			</div>
	</nav>


	{% with alerts = get_flashed_messages(with_categories=true) %}
	{% if alerts %}
	{% for category, text in alerts %}
	<div class="alert alert-{{ category }}">
		{{ text }}
		<button type="button" class="close" data-dismiss="alert" aria-label="close" style="float:right;">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	{% endfor %}
	{% endif %}
	{% endwith %}
</section>